import './main.js/preloader';
import './main.js/theme-switcher';
import './main.js/greetings';
import './main.js/library-btn-logic';
import './main.js/get-movies-by-genre';
import './main.js/save-genres';
import './main.js/modal';
import './main.js/footer-modal';
import './main.js/back-to-top';
